name: action di Bono #github action dice che ci deve essere una top level key name
on:  # dizionario con chiave push
  push: # una qualsiasi azione di push attiva questa action
jobs: 
  ciao:
    runs-on: ubuntu-latest # qui vuole il sistema operativo
    steps: #lista di comandi
      - uses: actions/checkout@v4
        with:
          sparse-checkout: | # il pipe serve a definire una stringa multilinea
            .github
            bono
      - run: ls -la
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - run: python --
      - run: pip install scikit-learn joblib pandas
      - run: python prova.py
        working-directory: bono
      - run: ls -la
        working-directory: bono
      - uses: actions/upload-artifact@v4
        with:
          name: best_species_classifier-v.0.0.1-RC
          path: bono/best_species_classifier.joblib
  inferenza:
    needs: ciao
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: | # il pipe serve a definire una stringa multilinea
            .github
            bono
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install scikit-learn joblib pandas pytest
      - uses: actions/download-artifact@v4
        with:
          path: bono/
      - run: pytest bono/